# simplex tableau

is structured

```
+---------------+-------------------+
| -c'_bB^(-1)b  |   c'-c'_b B^(-1)A |
+---------------+-------------------+
| B^(-1)b       |  B^(-1)A          |
+---------------+-------------------+
```
meaning:

```

+---------------------------------+-----------------------------+
|    current optim func cost      |  relative cost for each var |
+---------------------------------+-----------------------------+
| values of vars in current base  |  current const coeficients  |
+---------------------------------+-----------------------------+
```

We are minimaizing `-10x1 - 12x2-12x3`

with following constraints
```
1*x1 + 2*x2 + 2*x3 + x4 = 20
2*x1 + x2  + 2*x3 + x5 = 20
2*x1 + 2*x2  + x3 + x6 = 20
x1, ..., x6 >= 0
```

In [23]:
%load_ext autoreload
%autoreload 2
import numpy as np
import simplex as my
import time
import logging

logging.basicConfig(level=logging.INFO)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [24]:
A = np.array([[1, 1], 
              [0, 1], 
              [1, 2]])
b = np.array([0, 6, 3, 9])
c = np.array([2, 5])


In [25]:
A = np.array([[1, 2, 2], 
              [2, 1, 2], 
              [2, 2, 1]])
b = np.array([0,20, 20, 20])
c = np.array([-10, -12, -12])
A = A.reshape((3,3))

In [26]:
s = my.Simplex(A,b,c, "MIN")
print("A",s.A)
print("b",s.b)
print("c",s.c)

A [[1. 2. 2. 1. 0. 0.]
 [2. 1. 2. 0. 1. 0.]
 [2. 2. 1. 0. 0. 1.]]
b [ 0. 20. 20. 20.]
c [-10. -12. -12.   0.   0.   0.]


In [27]:
pass1 = s.optimize()

INFO:root:
 Iteration complete
 Table: 
 [[120.   -4.    0.    0.    6.    0.    0. ]
 [ 10.    0.5   1.    1.    0.5   0.    0. ]
 [ 10.    1.5   0.    1.   -0.5   1.    0. ]
 [  0.    1.    0.   -1.   -1.    0.    1. ]]


In [28]:
pass2 = s.optimize()

INFO:root:
 Iteration complete
 Table: 
 [[120.    0.    0.   -4.    2.    0.    4. ]
 [ 10.    0.    1.    1.5   1.    0.   -0.5]
 [ 10.    0.    0.    2.5   1.    1.   -1.5]
 [  0.    1.    0.   -1.   -1.    0.    1. ]]


In [29]:
pass2

array([[120. ,   0. ,   0. ,  -4. ,   2. ,   0. ,   4. ],
       [ 10. ,   0. ,   1. ,   1.5,   1. ,   0. ,  -0.5],
       [ 10. ,   0. ,   0. ,   2.5,   1. ,   1. ,  -1.5],
       [  0. ,   1. ,   0. ,  -1. ,  -1. ,   0. ,   1. ]])

In [30]:
s.optimize()
s.c

INFO:root:
 Iteration complete
 Table: 
 [[136.    0.    0.    0.    3.6   1.6   1.6]
 [  4.    0.    1.    0.    0.4  -0.6   0.4]
 [  4.    0.    0.    1.    0.4   0.4  -0.6]
 [  4.    1.    0.    0.   -0.6   0.4   0.4]]


array([0. , 0. , 0. , 3.6, 1.6, 1.6])

In [31]:
test_itr_1 = np.array([
[120.0,	-4.0,	0.0,	0.0,	6.0,	0.0,	0.0	],
[10.0,	0.5,	1.0,	1.0,	0.5,	0.0,	0.0	],
[10.0,	1.5,	0.0,	1.0,	-0.5,	1.0,	0.0	],
[0.0,	1.0,	0.0,	-1.0,	-1.0,	0.0,	1.0	]
])
assert(np.array_equiv(pass1, test_itr_1))

In [32]:
test_itr_2 = np.array([
[120.0, 0.0, 0.0, -4.0, 2.0, 0.0, 4.0],
[10.0,0.0,1.0,1.5,1.0,0.0,-0.5],
[10.0,0.0,0.0,2.5,1.0,	1.0,	-1.5],
[0.0,1.0,	0.0,	-1.0,	-1.0,	0.0,	1.0],
])
assert(np.array_equiv(pass2, test_itr_2))

In [33]:
s = my.Simplex(A,b,c, "MIN")
start = time.perf_counter()
print("result: ",s.simplex(4))
stop = time.perf_counter()
print("This all took: ",stop-start)
s.create_tab()

INFO:root:
 Iteration complete
 Table: 
 [[120.   -4.    0.    0.    6.    0.    0. ]
 [ 10.    0.5   1.    1.    0.5   0.    0. ]
 [ 10.    1.5   0.    1.   -0.5   1.    0. ]
 [  0.    1.    0.   -1.   -1.    0.    1. ]]
INFO:root:
 Iteration complete
 Table: 
 [[120.    0.    0.   -4.    2.    0.    4. ]
 [ 10.    0.    1.    1.5   1.    0.   -0.5]
 [ 10.    0.    0.    2.5   1.    1.   -1.5]
 [  0.    1.    0.   -1.   -1.    0.    1. ]]
INFO:root:
 Iteration complete
 Table: 
 [[136.    0.    0.    0.    3.6   1.6   1.6]
 [  4.    0.    1.    0.    0.4  -0.6   0.4]
 [  4.    0.    0.    1.    0.4   0.4  -0.6]
 [  4.    1.    0.    0.   -0.6   0.4   0.4]]
INFO:root:
 Iteration complete
 Table: 
 [[136.    0.    0.    0.    3.6   1.6   1.6]
 [  4.    0.    1.    0.    0.4  -0.6   0.4]
 [  4.    0.    0.    1.    0.4   0.4  -0.6]
 [  4.    1.    0.    0.   -0.6   0.4   0.4]]


result:  [4. 4. 4.]
This all took:  0.02633993001654744


array([[136. ,   0. ,   0. ,   0. ,   3.6,   1.6,   1.6],
       [  4. ,   0. ,   1. ,   0. ,   0.4,  -0.6,   0.4],
       [  4. ,   0. ,   0. ,   1. ,   0.4,   0.4,  -0.6],
       [  4. ,   1. ,   0. ,   0. ,  -0.6,   0.4,   0.4]])

In [34]:
img1 = np.array([[2,2],[2,4]])
img2 = np.array([[2,2],[2,2]])
print(img2-img1)
np.sum(img1 - img2)

[[ 0  0]
 [ 0 -2]]


2

In [35]:
A = [
    [1, -1, 0, 0],
    [1, 0, -1, 0],
    [-1, 1, 0, 0],
    [0, 1, 0, -1],
    [-1, 0, 1, 0],
    [0, 0, 1, -1],
    [0, -1, 0, 1],
    [0, 0, -1, 2],
]
len(A)
c = [-0,-0,-0,-2]
b = [0,1,1,1,1,1,1,1,1]
assert(len(b)==len(A)+1)
assert(len(A)==8)

In [36]:
s2 = my.Simplex(A,b,c,"MAX")
s2.optimize()

INFO:root:
 Iteration complete
 Table: 
 [[ 0.  0.  0.  0. -2.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1. -1.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1. -1.  0. -1.  1.  0.  0.  0.  0.  0.  0.]
 [ 2.  0.  0.  0.  0.  1.  0.  1.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0. -1.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 2.  0. -1.  1.  0.  1.  0.  0.  0.  1.  0.  0.  0.]
 [ 1.  0.  0.  1. -1.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 1.  0. -1.  0.  1.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 1.  0.  0. -1.  2.  0.  0.  0.  0.  0.  0.  0.  1.]]


array([[ 0.,  0.,  0.,  0., -2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1., -1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1., -1.,  0., -1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  0., -1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 2.,  0., -1.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  1., -1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 1.,  0., -1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 1.,  0.,  0., -1.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [37]:
res = s2.simplex()

INFO:root:
 Iteration complete
 Table: 
 [[ 0.  0.  0.  0. -2.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1. -1.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1. -1.  0. -1.  1.  0.  0.  0.  0.  0.  0.]
 [ 2.  0.  0.  0.  0.  1.  0.  1.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0. -1.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 2.  0. -1.  1.  0.  1.  0.  0.  0.  1.  0.  0.  0.]
 [ 1.  0.  0.  1. -1.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 1.  0. -1.  0.  1.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 1.  0.  0. -1.  2.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [38]:
print(res)
print(img1-img2)
s2.apply_func(img1-img2)
s2.b

[1. 0. 2. 1. 2. 1. 1. 1.]
[[0 0]
 [0 2]]


array([0., 1., 0., 2., 1., 2., 1., 1., 1.])

In [46]:
A = np.array([[1, 2, 3, 0], 
              [-1, 2, 6, 0], 
              [0, 4, 9, 0],
              [0, 0, 3, 1]])
b = np.array([0,3, 2, 5, 1])
c = np.array([1, 1, 1, 0])

s3 = my.Simplex(A,b,c,"MIN")
s3.simplex(10)

INFO:root:
 Iteration complete
 Table: 
 [[ 0.  1.  1.  1.  0.  0.  0.  0.  0.]
 [ 3.  1.  2.  3.  0.  1.  0.  0.  0.]
 [ 2. -1.  2.  6.  0.  0.  1.  0.  0.]
 [ 5.  0.  4.  9.  0.  0.  0.  1.  0.]
 [ 1.  0.  0.  3.  1.  0.  0.  0.  1.]]
INFO:root:
 Iteration complete
 Table: 
 [[ 0.  1.  1.  1.  0.  0.  0.  0.  0.]
 [ 3.  1.  2.  3.  0.  1.  0.  0.  0.]
 [ 2. -1.  2.  6.  0.  0.  1.  0.  0.]
 [ 5.  0.  4.  9.  0.  0.  0.  1.  0.]
 [ 1.  0.  0.  3.  1.  0.  0.  0.  1.]]
INFO:root:
 Iteration complete
 Table: 
 [[ 0.  1.  1.  1.  0.  0.  0.  0.  0.]
 [ 3.  1.  2.  3.  0.  1.  0.  0.  0.]
 [ 2. -1.  2.  6.  0.  0.  1.  0.  0.]
 [ 5.  0.  4.  9.  0.  0.  0.  1.  0.]
 [ 1.  0.  0.  3.  1.  0.  0.  0.  1.]]
INFO:root:
 Iteration complete
 Table: 
 [[ 0.  1.  1.  1.  0.  0.  0.  0.  0.]
 [ 3.  1.  2.  3.  0.  1.  0.  0.  0.]
 [ 2. -1.  2.  6.  0.  0.  1.  0.  0.]
 [ 5.  0.  4.  9.  0.  0.  0.  1.  0.]
 [ 1.  0.  0.  3.  1.  0.  0.  0.  1.]]
INFO:root:
 Iteration complete
 Table: 
 [[ 0.  1.  

array([3., 2., 5., 1.])

In [44]:
A = np.array([[1, 2, 3, 0], 
              [-1, 2, 6, 0], 
              [0, 4, 9, 0],
              [0, 0, 3, 1]])
b = np.array([0,3, 2, 5, 1])
c = np.array([1, 1, 1, 0])
s2 = my.Simplex(A,b,c,"MIN")
res = s2.simplex(10)

INFO:root:
 Iteration complete
 Table: 
 [[ 0.  1.  1.  1.  0.  0.  0.  0.  0.]
 [ 3.  1.  2.  3.  0.  1.  0.  0.  0.]
 [ 2. -1.  2.  6.  0.  0.  1.  0.  0.]
 [ 5.  0.  4.  9.  0.  0.  0.  1.  0.]
 [ 1.  0.  0.  3.  1.  0.  0.  0.  1.]]
INFO:root:
 Iteration complete
 Table: 
 [[ 0.  1.  1.  1.  0.  0.  0.  0.  0.]
 [ 3.  1.  2.  3.  0.  1.  0.  0.  0.]
 [ 2. -1.  2.  6.  0.  0.  1.  0.  0.]
 [ 5.  0.  4.  9.  0.  0.  0.  1.  0.]
 [ 1.  0.  0.  3.  1.  0.  0.  0.  1.]]
INFO:root:
 Iteration complete
 Table: 
 [[ 0.  1.  1.  1.  0.  0.  0.  0.  0.]
 [ 3.  1.  2.  3.  0.  1.  0.  0.  0.]
 [ 2. -1.  2.  6.  0.  0.  1.  0.  0.]
 [ 5.  0.  4.  9.  0.  0.  0.  1.  0.]
 [ 1.  0.  0.  3.  1.  0.  0.  0.  1.]]
INFO:root:
 Iteration complete
 Table: 
 [[ 0.  1.  1.  1.  0.  0.  0.  0.  0.]
 [ 3.  1.  2.  3.  0.  1.  0.  0.  0.]
 [ 2. -1.  2.  6.  0.  0.  1.  0.  0.]
 [ 5.  0.  4.  9.  0.  0.  0.  1.  0.]
 [ 1.  0.  0.  3.  1.  0.  0.  0.  1.]]
INFO:root:
 Iteration complete
 Table: 
 [[ 0.  1.  